package raymondseger.com.testandroidcomponents.classes;

import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;

public class UserRealmObject extends RealmObject {

    private String name;
    private String age;

    // Standard getters & setters generated by your IDE…
    public String getName() { return name; }
    public void   setName(String name) { this.name = name; }
    public String    getAge() { return age; }
    public void   setAge(String age) { this.age = age; }
}
